POST http://localhost:3000/login
Content-Type: application/json

{
	"username": "facu",
	"password": "facu"
}

###

GET http://localhost:3000/auth
Authorization: Bearer

###

GET http://localhost:3000/guest